site_name: GeoBTAA Metadata Handbook
site_author: Big Ten Academic Alliance Geospatial Information Network
copyright : "2025"
repo_url: https://github.com/geobtaa/metadata
theme:
      name: material
      font:
            text: helvetica neue
      features:
            - navigation.sections
            - content.tooltips
            - navigation.tabs
            - navigation.tabs.sticky
            - navigation.top
      logo: images/btaa-logo-white.png
      highlightjs: true
plugins:
      - search
      - table-reader
#             - git-revision-date-localized:
#                   enable_creation_date: true
#             - with-pdf:
#                   output_path: export/b1g-handbook.pdf
extra_css:
      - stylesheets/extra.css

markdown_extensions:
      - abbr
      - def_list
      - footnotes
      - tables
      - attr_list
      - md_in_html
      - admonition
      - pymdownx.critic
      - pymdownx.caret
      - pymdownx.keys
      - pymdownx.mark
      - pymdownx.tilde
      - pymdownx.details
      - pymdownx.superfences
      - pymdownx.snippets
      - pymdownx.emoji:
            emoji_index: !!python/name:material.extensions.emoji.twemoji
            emoji_generator: !!python/name:material.extensions.emoji.to_svg
            options:
                  custom_icons:
                        - overrides/.icons
      - pymdownx.tabbed:
            alternate_style: true
            slugify: !!python/object/apply:pymdownx.slugs.slugify
                  kwds:
                        case: lower
      - toc:
            toc_depth: 2
            permalink: true
      - def_list
      - pymdownx.tasklist:
            custom_checkbox: true
      - pymdownx.snippets:
            auto_append:
              - includes/abbreviations.md
      - admonition
      - pymdownx.details
      - pymdownx.magiclink
      - pymdownx.superfences:
            custom_fences:
                  - name: mermaid
                    class: mermaid
                    format: !!python/name:pymdownx.superfences.fence_code_format
                    showSequenceNumbers: true
                    noteFontWeight: "10px"
                    actorFontSize: "10px"
                    messageFontSize: "10px"
      - pymdownx.tabbed:
            alternate_style: true


nav:
- HOME: 'index.md'
  
- Reference:
      - Schema:
            - 'GeoBTAA Metadata Profile': 'geobtaa-metadata-application-profile.md'
            - 'Custom Elements' : 'b1g-custom-elements.md'
            - 'Editing Template' : 'editingTemplate.md'
      - Guidelines:
            - 'Submit Resources' : 'submit-resources.md'
            - 'Local Input Guidelines': 'input-guidelines.md'
            
            
      - 'Glossary': 'glossary.md'
      
- Explanation:
      - Metadata Workflows:
            - 'Resource Lifecycle' : 'resource-lifecycle.md'
            - 'ArcGIS Hubs' : 'arcgis-hub-guidelines.md'
      - Content Organization:
            - 'Content Organization Model' : 'model.md'
            - 'Resource Classes' : 'resourceClasses.md'
            - 'Supplemental Metadata' : 'supplementalMetadata.md'
      - Harvesting:
            - 'About Metadata Harvesting' : 'about-harvesting.md'
            - 'Ephemeral Data' : 'ephemeral-data.md'
            - 'Harvest Schedule': 'schedule.md'
            - 'DCAT Metadata' : 'dcat.md'
            - 'CKAN Data Portals' : 'ckan.md'
            
- Tutorials: 
      - 'Harvesting': 'tutorials/python-jupyter.md' 
      - 'Orientation': 'tutorials/orientation.md'

- Recipes:  
      - 'About': 'recipes/index.md'
      - Harvest:
            - 'ArcGIS': 'recipes/R-01_arcgis-hubs.md'
            - 'Socrata': 'recipes/R-02_socrata.md'
            - 'CKAN': 'recipes/R-03_ckan.md'
            - 'OAI-PMH': 'recipes/R-04_oai-pmh.md'
            - 'IIIF': 'recipes/R-05_iiif.md'
            - 'MODS': 'recipes/R-06_mods.md'
            - 'OpenGeoMetadata': 'recipes/R-07_ogm.md'
            - 'PASDA' : 'recipes/R-08_pasda.md'
            - 'UMedia' : 'recipes/R-09_umedia.md'
                  
      - Edit:   
            - 'Validate and Clean': 'recipes/clean.md'
            - 'Add bounding boxes': 'recipes/add-bbox.md'
            - 'Split bounding boxes': 'recipes/split-bbox.md'
            - 'Standardize Creator names': 'recipes/standardize-creators.md'
            - 'Update ArcGIS Hubs list': 'recipes/update-hub-list.md'
            - 'Multiple links in GEOMG': 'recipes/secondary-tables.md'
      
      